using WDBXEditor.Reader.FileTypes;
using WDBXEditor.Storage;
using System.IO;
using System.Linq;
using System.Text;
using WDBXEditor.Common;
using System.Collections.Generic;
using System;

namespace WDBXEditor.Reader
{
    public class DBHeader
    {
        //Standard Fields
        public string Signature { get; set; }
        public uint RecordCount { get; set; }
        public uint UnknownWCH7 { get; set; }
        public uint FieldCount { get; set; }
        public uint RecordSize { get; set; }
        public uint StringBlockSize { get; set; }

        public ushort IdIndex { get; set; } = 0;
        public int AutoGeneratedColumns { get; set; } = 0;
        public int[] OffsetLengths { get; set; } = new int[0];
        public int HeaderSize = 0x20;
        public int StringTableOffset = 0x10;

        public bool IsWDBFile => this is WDB;
        public bool IsWDBCFile => this is WDBC;
        public bool IsWDB2File => this is WDB2;
        public bool IsWDB5File => this is WDB5;
        public bool IsWCH5File => this is WCH5;
        public bool IsWCH7File => this is WCH7;
        public bool IsLegionFile => this is WDB5 || this is WCH5 || this is WCH7;
        public bool IsValidFile => (IsWDBFile || IsWDB2File || IsWDBCFile || IsLegionFile);

        public virtual bool ExtendedStringTable => false;
        public virtual bool HasIndexTable => false;
        public virtual bool HasOffsetTable => false;
        public virtual bool HasSecondIndex => false;        

        public Dictionary<int, int> OffsetDuplicates = new Dictionary<int, int>();

        public virtual void ReadHeader(ref BinaryReader dbReader, string signature)
        {
            this.Signature = signature;
            RecordCount = dbReader.ReadUInt32();

            if (IsWCH7File)
                UnknownWCH7 = dbReader.ReadUInt32();

            FieldCount = dbReader.ReadUInt32();
            RecordSize = dbReader.ReadUInt32();
            StringBlockSize = dbReader.ReadUInt32();
        }

        public virtual byte[] ReadData(BinaryReader dbReader, long pos) { return new byte[0]; }

        public virtual void WriteHeader(BinaryWriter bw, DBEntry entry)
        {
            //Signature
            bw.Write(Encoding.UTF8.GetBytes(Signature));

            //Record count
            if (IsWDB5File && !(this as WDB5).HasOffsetTable)
                bw.Write(entry.GetUniqueRows().Count());
            else
                bw.Write(entry.Data.Rows.Count);

            //WCH7 specific field
            if (IsWCH7File)
                bw.Write(UnknownWCH7);

            //FieldCount
            if (IsWDB5File)
                bw.Write(((WDB5)this).HasIndexTable ? FieldCount - 1 : FieldCount); //Index Table
            else
                bw.Write(FieldCount);

            //Record size
            bw.Write(RecordSize);

            //StringBlockSize placeholder
            if (IsWDB5File || IsWCH7File)
                bw.Write((uint)2);
            else
                bw.Write((uint)1);
        }

        public virtual void WriteOffsetMap(BinaryWriter bw, DBEntry entry, List<Tuple<int, short>> OffsetMap) { }

        public virtual void WriteIndexTable(BinaryWriter bw, DBEntry entry) { }

        public virtual void WriteRecordPadding(BinaryWriter bw, DBEntry entry, long offset)
        {
            if (bw.BaseStream.Position - offset < RecordSize)
                bw.BaseStream.Position += (RecordSize - (bw.BaseStream.Position - offset));
        }
    }
}
