using WDBXEditor.Common;

namespace WDBXEditor
{
    partial class EditDefinition
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
			System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(EditDefinition));
			this.dgvDefintion = new System.Windows.Forms.DataGridView();
			this.btnSave = new System.Windows.Forms.Button();
			this.txtBuild = new System.Windows.Forms.TextBox();
			this.label1 = new System.Windows.Forms.Label();
			this.txtFileName = new System.Windows.Forms.TextBox();
			this.label3 = new System.Windows.Forms.Label();
			this.btnNew = new System.Windows.Forms.Button();
			this.label2 = new System.Windows.Forms.Label();
			this.txtFilter = new System.Windows.Forms.TextBox();
			this.btnCopy = new System.Windows.Forms.Button();
			this.groupBox1 = new System.Windows.Forms.GroupBox();
			this.btnDelete = new System.Windows.Forms.Button();
			this.groupBox2 = new System.Windows.Forms.GroupBox();
			this.btnReset = new System.Windows.Forms.Button();
			this.cbBuild = new System.Windows.Forms.ComboBox();
			this.label4 = new System.Windows.Forms.Label();
			this.dataGridViewTextBoxColumn1 = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.dataGridViewComboBoxColumn1 = new System.Windows.Forms.DataGridViewComboBoxColumn();
			this.dataGridViewCheckBoxColumn1 = new System.Windows.Forms.DataGridViewCheckBoxColumn();
			this.dataGridViewCheckBoxColumn2 = new System.Windows.Forms.DataGridViewCheckBoxColumn();
			this.dataGridViewTextBoxColumn2 = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.dataGridViewTextBoxColumn3 = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.dataGridViewTextBoxColumn4 = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.lbFiles = new WDBXEditor.Common.BufferedListBox();
			this.colField = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.colType = new System.Windows.Forms.DataGridViewComboBoxColumn();
			this.colIndex = new System.Windows.Forms.DataGridViewCheckBoxColumn();
			this.colAutoGenerated = new System.Windows.Forms.DataGridViewCheckBoxColumn();
			this.colArraySize = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.colSparse = new System.Windows.Forms.DataGridViewCheckBoxColumn();
			this.colDefaultValue = new System.Windows.Forms.DataGridViewTextBoxColumn();
			this.colColumnNames = new System.Windows.Forms.DataGridViewTextBoxColumn();
			((System.ComponentModel.ISupportInitialize)(this.dgvDefintion)).BeginInit();
			this.groupBox1.SuspendLayout();
			this.groupBox2.SuspendLayout();
			this.SuspendLayout();
			// 
			// dgvDefintion
			// 
			this.dgvDefintion.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
			this.dgvDefintion.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
			this.dgvDefintion.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.colField,
            this.colType,
            this.colIndex,
            this.colAutoGenerated,
            this.colArraySize,
            this.colSparse,
            this.colDefaultValue,
            this.colColumnNames});
			this.dgvDefintion.Location = new System.Drawing.Point(319, 12);
			this.dgvDefintion.Name = "dgvDefintion";
			this.dgvDefintion.RowHeadersVisible = false;
			this.dgvDefintion.Size = new System.Drawing.Size(630, 428);
			this.dgvDefintion.TabIndex = 0;
			this.dgvDefintion.CellMouseDown += new System.Windows.Forms.DataGridViewCellMouseEventHandler(this.dgvDefintion_CellMouseDown);
			this.dgvDefintion.CellValueChanged += new System.Windows.Forms.DataGridViewCellEventHandler(this.dgvDefintion_CellValueChanged);
			this.dgvDefintion.DataBindingComplete += new System.Windows.Forms.DataGridViewBindingCompleteEventHandler(this.dgvDefintion_DataBindingComplete);
			this.dgvDefintion.RowPostPaint += new System.Windows.Forms.DataGridViewRowPostPaintEventHandler(this.dgvDefintion_RowPostPaint);
			// 
			// btnSave
			// 
			this.btnSave.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
			this.btnSave.Location = new System.Drawing.Point(244, 71);
			this.btnSave.Name = "btnSave";
			this.btnSave.Size = new System.Drawing.Size(70, 23);
			this.btnSave.TabIndex = 7;
			this.btnSave.Text = "Save";
			this.btnSave.UseVisualStyleBackColor = true;
			this.btnSave.Click += new System.EventHandler(this.btnSave_Click);
			// 
			// txtBuild
			// 
			this.txtBuild.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
			this.txtBuild.Location = new System.Drawing.Point(46, 19);
			this.txtBuild.Name = "txtBuild";
			this.txtBuild.Size = new System.Drawing.Size(268, 20);
			this.txtBuild.TabIndex = 2;
			// 
			// label1
			// 
			this.label1.AutoSize = true;
			this.label1.Location = new System.Drawing.Point(4, 22);
			this.label1.Name = "label1";
			this.label1.Size = new System.Drawing.Size(36, 13);
			this.label1.TabIndex = 0;
			this.label1.Text = "Build: ";
			// 
			// txtFileName
			// 
			this.txtFileName.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
			this.txtFileName.Location = new System.Drawing.Point(46, 45);
			this.txtFileName.Name = "txtFileName";
			this.txtFileName.Size = new System.Drawing.Size(268, 20);
			this.txtFileName.TabIndex = 3;
			// 
			// label3
			// 
			this.label3.AutoSize = true;
			this.label3.Location = new System.Drawing.Point(4, 48);
			this.label3.Name = "label3";
			this.label3.Size = new System.Drawing.Size(29, 13);
			this.label3.TabIndex = 4;
			this.label3.Text = "File: ";
			// 
			// btnNew
			// 
			this.btnNew.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
			this.btnNew.Location = new System.Drawing.Point(168, 71);
			this.btnNew.Name = "btnNew";
			this.btnNew.Size = new System.Drawing.Size(70, 23);
			this.btnNew.TabIndex = 6;
			this.btnNew.Text = "New";
			this.btnNew.UseVisualStyleBackColor = true;
			this.btnNew.Click += new System.EventHandler(this.btnNew_Click);
			// 
			// label2
			// 
			this.label2.AutoSize = true;
			this.label2.Location = new System.Drawing.Point(5, 22);
			this.label2.Name = "label2";
			this.label2.Size = new System.Drawing.Size(29, 13);
			this.label2.TabIndex = 1;
			this.label2.Text = "Filter";
			// 
			// txtFilter
			// 
			this.txtFilter.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
			this.txtFilter.Location = new System.Drawing.Point(47, 19);
			this.txtFilter.Name = "txtFilter";
			this.txtFilter.Size = new System.Drawing.Size(255, 20);
			this.txtFilter.TabIndex = 2;
			this.txtFilter.TextChanged += new System.EventHandler(this.txtFilter_TextChanged);
			// 
			// btnCopy
			// 
			this.btnCopy.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
			this.btnCopy.Location = new System.Drawing.Point(92, 71);
			this.btnCopy.Name = "btnCopy";
			this.btnCopy.Size = new System.Drawing.Size(70, 23);
			this.btnCopy.TabIndex = 5;
			this.btnCopy.Text = "Copy";
			this.btnCopy.UseVisualStyleBackColor = true;
			this.btnCopy.Click += new System.EventHandler(this.btnCopy_Click);
			// 
			// groupBox1
			// 
			this.groupBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
			this.groupBox1.Controls.Add(this.btnDelete);
			this.groupBox1.Controls.Add(this.btnCopy);
			this.groupBox1.Controls.Add(this.txtFileName);
			this.groupBox1.Controls.Add(this.label3);
			this.groupBox1.Controls.Add(this.btnSave);
			this.groupBox1.Controls.Add(this.btnNew);
			this.groupBox1.Controls.Add(this.label1);
			this.groupBox1.Controls.Add(this.txtBuild);
			this.groupBox1.Location = new System.Drawing.Point(629, 446);
			this.groupBox1.Name = "groupBox1";
			this.groupBox1.Size = new System.Drawing.Size(320, 104);
			this.groupBox1.TabIndex = 4;
			this.groupBox1.TabStop = false;
			this.groupBox1.Text = "Actions";
			// 
			// btnDelete
			// 
			this.btnDelete.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
			this.btnDelete.Location = new System.Drawing.Point(16, 71);
			this.btnDelete.Name = "btnDelete";
			this.btnDelete.Size = new System.Drawing.Size(70, 23);
			this.btnDelete.TabIndex = 4;
			this.btnDelete.Text = "Delete";
			this.btnDelete.UseVisualStyleBackColor = true;
			this.btnDelete.Click += new System.EventHandler(this.btnDelete_Click);
			// 
			// groupBox2
			// 
			this.groupBox2.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
			this.groupBox2.Controls.Add(this.btnReset);
			this.groupBox2.Controls.Add(this.cbBuild);
			this.groupBox2.Controls.Add(this.label4);
			this.groupBox2.Controls.Add(this.txtFilter);
			this.groupBox2.Controls.Add(this.label2);
			this.groupBox2.Location = new System.Drawing.Point(319, 446);
			this.groupBox2.Name = "groupBox2";
			this.groupBox2.Size = new System.Drawing.Size(308, 104);
			this.groupBox2.TabIndex = 3;
			this.groupBox2.TabStop = false;
			this.groupBox2.Text = "Filter";
			// 
			// btnReset
			// 
			this.btnReset.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
			this.btnReset.Location = new System.Drawing.Point(232, 71);
			this.btnReset.Name = "btnReset";
			this.btnReset.Size = new System.Drawing.Size(70, 23);
			this.btnReset.TabIndex = 9;
			this.btnReset.Text = "Reset";
			this.btnReset.UseVisualStyleBackColor = true;
			this.btnReset.Click += new System.EventHandler(this.btnReset_Click);
			// 
			// cbBuild
			// 
			this.cbBuild.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
			this.cbBuild.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cbBuild.FormattingEnabled = true;
			this.cbBuild.Location = new System.Drawing.Point(47, 45);
			this.cbBuild.Name = "cbBuild";
			this.cbBuild.Size = new System.Drawing.Size(255, 21);
			this.cbBuild.TabIndex = 4;
			this.cbBuild.SelectedIndexChanged += new System.EventHandler(this.cbBuild_SelectedIndexChanged);
			// 
			// label4
			// 
			this.label4.AutoSize = true;
			this.label4.Location = new System.Drawing.Point(5, 48);
			this.label4.Name = "label4";
			this.label4.Size = new System.Drawing.Size(30, 13);
			this.label4.TabIndex = 3;
			this.label4.Text = "Build";
			// 
			// dataGridViewTextBoxColumn1
			// 
			this.dataGridViewTextBoxColumn1.DataPropertyName = "Name";
			this.dataGridViewTextBoxColumn1.FillWeight = 113.518F;
			this.dataGridViewTextBoxColumn1.HeaderText = "Field";
			this.dataGridViewTextBoxColumn1.Name = "dataGridViewTextBoxColumn1";
			this.dataGridViewTextBoxColumn1.Width = 145;
			// 
			// dataGridViewComboBoxColumn1
			// 
			this.dataGridViewComboBoxColumn1.DataPropertyName = "Type";
			this.dataGridViewComboBoxColumn1.FillWeight = 75.67866F;
			this.dataGridViewComboBoxColumn1.HeaderText = "Type";
			this.dataGridViewComboBoxColumn1.Items.AddRange(new object[] {
            "bool",
            "byte",
            "float",
            "int",
            "loc",
            "long",
            "sbyte",
            "short",
            "string",
            "uint",
            "ulong",
            "ushort"});
			this.dataGridViewComboBoxColumn1.Name = "dataGridViewComboBoxColumn1";
			this.dataGridViewComboBoxColumn1.Sorted = true;
			this.dataGridViewComboBoxColumn1.Width = 97;
			// 
			// dataGridViewCheckBoxColumn1
			// 
			this.dataGridViewCheckBoxColumn1.DataPropertyName = "IsIndex";
			this.dataGridViewCheckBoxColumn1.FillWeight = 56.759F;
			this.dataGridViewCheckBoxColumn1.HeaderText = "Index";
			this.dataGridViewCheckBoxColumn1.Name = "dataGridViewCheckBoxColumn1";
			this.dataGridViewCheckBoxColumn1.Width = 72;
			// 
			// dataGridViewCheckBoxColumn2
			// 
			this.dataGridViewCheckBoxColumn2.DataPropertyName = "AutoGenerate";
			this.dataGridViewCheckBoxColumn2.FillWeight = 75.67866F;
			this.dataGridViewCheckBoxColumn2.HeaderText = "AutoGenerated";
			this.dataGridViewCheckBoxColumn2.Name = "dataGridViewCheckBoxColumn2";
			this.dataGridViewCheckBoxColumn2.Width = 97;
			// 
			// dataGridViewTextBoxColumn2
			// 
			this.dataGridViewTextBoxColumn2.DataPropertyName = "ArraySize";
			this.dataGridViewTextBoxColumn2.FillWeight = 56.759F;
			this.dataGridViewTextBoxColumn2.HeaderText = "ArraySize";
			this.dataGridViewTextBoxColumn2.Name = "dataGridViewTextBoxColumn2";
			this.dataGridViewTextBoxColumn2.Width = 72;
			// 
			// dataGridViewTextBoxColumn3
			// 
			this.dataGridViewTextBoxColumn3.DataPropertyName = "Padding";
			this.dataGridViewTextBoxColumn3.FillWeight = 56.759F;
			this.dataGridViewTextBoxColumn3.HeaderText = "Padding";
			this.dataGridViewTextBoxColumn3.Name = "dataGridViewTextBoxColumn3";
			this.dataGridViewTextBoxColumn3.Width = 73;
			// 
			// dataGridViewTextBoxColumn4
			// 
			this.dataGridViewTextBoxColumn4.DataPropertyName = "DefaultValue";
			this.dataGridViewTextBoxColumn4.FillWeight = 56F;
			this.dataGridViewTextBoxColumn4.HeaderText = "Default";
			this.dataGridViewTextBoxColumn4.Name = "dataGridViewTextBoxColumn4";
			this.dataGridViewTextBoxColumn4.Width = 71;
			// 
			// lbFiles
			// 
			this.lbFiles.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left)));
			this.lbFiles.FormattingEnabled = true;
			this.lbFiles.HorizontalScrollbar = true;
			this.lbFiles.Location = new System.Drawing.Point(12, 12);
			this.lbFiles.Name = "lbFiles";
			this.lbFiles.Size = new System.Drawing.Size(301, 537);
			this.lbFiles.TabIndex = 1;
			this.lbFiles.MouseDoubleClick += new System.Windows.Forms.MouseEventHandler(this.lbFiles_MouseDoubleClick);
			// 
			// colField
			// 
			this.colField.DataPropertyName = "Name";
			this.colField.FillWeight = 113.518F;
			this.colField.HeaderText = "Field";
			this.colField.Name = "colField";
			// 
			// colType
			// 
			this.colType.DataPropertyName = "Type";
			this.colType.FillWeight = 75.67866F;
			this.colType.HeaderText = "Type";
			this.colType.Items.AddRange(new object[] {
            "bool",
            "byte",
            "float",
            "int",
            "loc",
            "long",
            "sbyte",
            "short",
            "string",
            "uint",
            "ulong",
            "ushort"});
			this.colType.Name = "colType";
			this.colType.Sorted = true;
			// 
			// colIndex
			// 
			this.colIndex.DataPropertyName = "IsIndex";
			this.colIndex.FillWeight = 56.759F;
			this.colIndex.HeaderText = "Index";
			this.colIndex.Name = "colIndex";
			// 
			// colAutoGenerated
			// 
			this.colAutoGenerated.DataPropertyName = "AutoGenerate";
			this.colAutoGenerated.FillWeight = 75.67866F;
			this.colAutoGenerated.HeaderText = "AutoGenerated";
			this.colAutoGenerated.Name = "colAutoGenerated";
			// 
			// colArraySize
			// 
			this.colArraySize.DataPropertyName = "ArraySize";
			this.colArraySize.FillWeight = 56.759F;
			this.colArraySize.HeaderText = "ArraySize";
			this.colArraySize.Name = "colArraySize";
			// 
			// colSparse
			// 
			this.colSparse.DataPropertyName = "Sparse";
			this.colSparse.FillWeight = 56.759F;
			this.colSparse.HeaderText = "Sparse";
			this.colSparse.Name = "colSparse";
			this.colSparse.Resizable = System.Windows.Forms.DataGridViewTriState.True;
			this.colSparse.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.Automatic;
			this.colSparse.Visible = false;
			// 
			// colDefaultValue
			// 
			this.colDefaultValue.DataPropertyName = "DefaultValue";
			this.colDefaultValue.FillWeight = 75.67866F;
			this.colDefaultValue.HeaderText = "DefaultValue";
			this.colDefaultValue.Name = "colDefaultValue";
			// 
			// colColumnNames
			// 
			this.colColumnNames.DataPropertyName = "ColumnNames";
			this.colColumnNames.HeaderText = "ColumnNames";
			this.colColumnNames.Name = "colColumnNames";
			// 
			// EditDefinition
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.ClientSize = new System.Drawing.Size(961, 561);
			this.Controls.Add(this.groupBox2);
			this.Controls.Add(this.groupBox1);
			this.Controls.Add(this.lbFiles);
			this.Controls.Add(this.dgvDefintion);
			this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.MinimumSize = new System.Drawing.Size(960, 600);
			this.Name = "EditDefinition";
			this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
			this.Text = "Edit Definition";
			this.Load += new System.EventHandler(this.EditDefinition_Load);
			((System.ComponentModel.ISupportInitialize)(this.dgvDefintion)).EndInit();
			this.groupBox1.ResumeLayout(false);
			this.groupBox1.PerformLayout();
			this.groupBox2.ResumeLayout(false);
			this.groupBox2.PerformLayout();
			this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.DataGridView dgvDefintion;
        private BufferedListBox lbFiles;
        private System.Windows.Forms.TextBox txtBuild;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Button btnSave;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.TextBox txtFilter;
        private System.Windows.Forms.Button btnNew;
        private System.Windows.Forms.TextBox txtFileName;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Button btnCopy;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.Button btnDelete;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.ComboBox cbBuild;
        private System.Windows.Forms.Button btnReset;
        private System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn1;
        private System.Windows.Forms.DataGridViewComboBoxColumn dataGridViewComboBoxColumn1;
        private System.Windows.Forms.DataGridViewCheckBoxColumn dataGridViewCheckBoxColumn1;
        private System.Windows.Forms.DataGridViewCheckBoxColumn dataGridViewCheckBoxColumn2;
        private System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn2;
        private System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn3;
        private System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn4;
		private System.Windows.Forms.DataGridViewTextBoxColumn colField;
		private System.Windows.Forms.DataGridViewComboBoxColumn colType;
		private System.Windows.Forms.DataGridViewCheckBoxColumn colIndex;
		private System.Windows.Forms.DataGridViewCheckBoxColumn colAutoGenerated;
		private System.Windows.Forms.DataGridViewTextBoxColumn colArraySize;
		private System.Windows.Forms.DataGridViewCheckBoxColumn colSparse;
		private System.Windows.Forms.DataGridViewTextBoxColumn colDefaultValue;
		private System.Windows.Forms.DataGridViewTextBoxColumn colColumnNames;
	}
}